inherits = "tokyonight"

attribute = { fg = "fg" }
comment = { fg = "fg", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "fg" }
constant = { fg = "fg" }
"constant.builtin" = { fg = "fg" }
"constant.character" = { fg = "fg" }
"constant.character.escape" = { fg = "fg" }
constructor = { fg = "fg" }
function = { fg = "fg", modifiers = ["italic"] }
"function.builtin" = { fg = "fg" }
"function.macro" = { fg = "fg" }
"function.special" = { fg = "fg" }
keyword = { fg = "fg", modifiers = ["italic"] }
"keyword.control" = { fg = "fg" }
"keyword.control.import" = { fg = "fg" }
"keyword.control.return" = { fg = "fg", modifiers = ["italic"] }
"keyword.directive" = { fg = "fg" }
"keyword.function" = { fg = "fg" }
"keyword.operator" = { fg = "fg" }
label = { fg = "fg" }
namespace = { fg = "fg" }
operator = { fg = "fg" }
punctuation = { fg = "fg" }
special = { fg = "fg" }
string = { fg = "fg" }
"string.regexp" = { fg = "fg" }
"string.special" = { fg = "fg" }
tag = { fg = "fg" }
type = { fg = "fg" }
"type.builtin" = { fg = "fg" }
"type.enum.variant" = { fg = "fg" }
variable = { fg = "fg" }
"variable.builtin" = { fg = "fg" }
"variable.other.member" = { fg = "fg" }
"variable.parameter" = { fg = "fg", modifiers = ["italic"] }

"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "fg", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "bg-menu", fg = "fg" }
"markup.heading.hover" = { bg = "fg-selected" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "fg", underline = { style = "line" } }
"markup.link.label" = { fg = "fg" }
"markup.link.text" = { fg = "fg" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "fg", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "fg" }
"markup.normal.hover" = { fg = "fg" }
"markup.raw" = { fg = "fg" }
"markup.raw.inline" = { bg = "black", fg = "fg" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diff.delta" = { fg = "fg" }
"diff.delta.moved" = { fg = "fg" }
"diff.minus" = { fg = "fg" }
"diff.plus" = { fg = "fg" }

error = { fg = "fg" }
warning = { fg = "fg" }
info = { fg = "fg" }
hint = { fg = "fg" }
"diagnostic.error" = { underline = { style = "curl", color = "fg" } }
"diagnostic.warning" = { underline = { style = "curl", color = "fg"} }
"diagnostic.info" = { underline = { style = "curl", color = "fg"} }
"diagnostic.hint" = { underline = { style = "curl", color = "fg" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"ui.background" = { bg = "bg", fg = "fg" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "fg", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "bg-menu" }
"ui.help" = { bg = "bg-menu", fg = "fg" }
"ui.linenr" = { fg = "fg" }
"ui.linenr.selected" = { fg = "fg" }
"ui.menu" = { bg = "bg-menu", fg = "fg" }
"ui.menu.selected" = { bg = "fg-selected" }
"ui.popup" = { bg = "bg-menu", fg = "fg" }
"ui.selection" = { bg = "bg-selection" }
"ui.selection.primary" = { bg = "bg-selection" }
"ui.statusline" = { bg = "bg-menu", fg = "fg" }
"ui.statusline.inactive" = { bg = "bg-menu", fg = "fg" }
"ui.statusline.normal" = { bg = "bg", fg = "fg", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "bg", fg = "fg", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "bg", fg = "fg", modifiers = ["bold"] }
"ui.text" = { fg = "fg" }
"ui.text.focus" = { bg = "bg-focus" }
"ui.text.inactive" = { fg = "fg", modifiers = ["italic"] }
"ui.text.info" = { bg = "bg-menu", fg = "fg" }
"ui.text.directory" = { fg = "fg" }
"ui.virtual.ruler" = { bg = "fg" }
"ui.virtual.whitespace" = { fg = "fg" }
"ui.virtual.inlay-hint" = {  bg = "bg-inlay", fg = "fg" }
"ui.virtual.jump-label" = {  fg = "fg", modifiers = ["bold"] }
"ui.window" = { fg = "fg", modifiers = ["bold"] }

[palette]
fg = "#ffffff"
bg = "#14228e"
bg-menu = "#16161e"
bg-focus = "#292e42"
bg-selection = "#283457"
bg-inlay = "#1a2b32"
fg-selected = "#343a55"

