export ZSH="$HOME/.oh-my-zsh"

eval "$(direnv hook zsh)"

# NIX MODE INDICATOR
if [[ "$IN_DEV_SHELL" == "1" ]]; then
  NIX_SHELL_INDICATOR="%F{cyan}[nix develop]%f "
else
  NIX_SHELL_INDICATOR=""
fi

PROMPT="${NIX_SHELL_INDICATOR}%F{white}%n@%m%f:%F{white}%~%f %# "

# femboy things
export PATH="$HOME/.cargo/bin:$PATH"

export PATH="$HOME/.local/node_modules/.bin:$PATH"

#cartesi
export PATH=$HOME/.npm-global/bin:$PATH
