export ZSH="$HOME/.oh-my-zsh"

# NIX MODE INDICATOR
if [[ "$IN_NIX_SHELL" == "pure" || "$IN_NIX_SHELL" == "1" ]]; then
  NIX_SHELL_INDICATOR="%F{red}[nix develop]%f "
else
  NIX_SHELL_INDICATOR=""
fi

# Set prompt
PROMPT='${NIX_SHELL_INDICATOR}%F{cyan}%n@%m%f:%F{green}%~%f %# '
